# Generated by Django 2.1.1 on 2019-04-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorFirstName', models.CharField(max_length=100)),
                ('doctorMiddleName', models.CharField(max_length=100)),
                ('doctorLastName', models.CharField(max_length=100)),
                ('Gender', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientFirstName', models.CharField(max_length=100)),
                ('patientMiddleName', models.CharField(max_length=100)),
                ('patientLastName', models.CharField(max_length=100)),
                ('Gender', models.BooleanField()),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
            ],
        ),
    ]
