# Generated by Django 2.1.1 on 2019-05-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.IntegerField(choices=[(0, 'O+'), (1, 'O-'), (2, 'B-'), (3, 'B+'), (4, 'A-'), (5, 'A+'), (6, 'AB-'), (7, 'AB+')]),
        ),
    ]
