# Generated by Django 2.1.1 on 2019-05-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20190526_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='acc_type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Doctor'), (2, 'LabAssistant'), (3, 'Patient'), (4, 'Admin')], default=0),
        ),
    ]
