# Generated by Django 2.1.1 on 2019-04-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20190410_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_middle_name',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='doctorID',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_middle_name',
            new_name='middle_name',
        ),
    ]
