# Generated by Django 2.1.1 on 2019-04-21 07:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20190410_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application', models.DateTimeField()),
                ('date_registration', models.DateTimeField()),
                ('date_taking_material', models.DateTimeField()),
                ('target_date', models.DateTimeField()),
                ('material', models.CharField(max_length=45)),
                ('diagnosis', models.CharField(max_length=45)),
                ('delivering_method', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='doctor',
            name='exam_room',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='doctor',
            name='post',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='middle_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AddField(
            model_name='timeschedule',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
        migrations.AddField(
            model_name='medicaltests',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Patient'),
        ),
    ]
