# Generated by Django 2.1.1 on 2019-05-26 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20190526_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='doc_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
    ]
