# Generated by Django 2.1.1 on 2019-04-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20190421_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.BooleanField(choices=[(0, 'Male'), (1, 'Female')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.BooleanField(choices=[(0, 'Male'), (1, 'Female')]),
        ),
    ]
