# Generated by Django 2.1.1 on 2019-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20190424_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltests',
            name='readiness',
            field=models.BooleanField(choices=[(0, 'In progress'), (1, 'Ready')], default=0),
        ),
    ]
