# Generated by Django 2.1.1 on 2019-05-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20190528_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.BooleanField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.BooleanField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
    ]
