# Generated by Django 2.1.1 on 2019-05-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20190528_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeschedule',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='patient_id',
        ),
        migrations.DeleteModel(
            name='TimeSchedule',
        ),
    ]
