# Generated by Django 2.1.1 on 2019-04-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20190428_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltests',
            name='date_application',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicaltests',
            name='date_registration',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicaltests',
            name='date_taking_material',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicaltests',
            name='target_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
