# Generated by Django 2.1.1 on 2019-06-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20190602_1753'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('day', 'time', 'doctor_id')},
        ),
    ]
