# Generated by Django 2.1.1 on 2019-04-28 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20190428_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltests',
            name='date_application',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicaltests',
            name='date_registration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicaltests',
            name='date_taking_material',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicaltests',
            name='target_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
