# Generated by Django 2.1.1 on 2019-04-28 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20190428_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
