# Generated by Django 2.1.1 on 2019-05-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_auto_20190428_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeschedule',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeschedule',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
