# Generated by Django 2.1.1 on 2019-05-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_auto_20190512_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeschedule',
            options={'verbose_name': 'Scheduling', 'verbose_name_plural': 'Scheduling'},
        ),
    ]
