# Generated by Django 2.1.1 on 2019-05-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_auto_20190512_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeschedule',
            options={},
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='day_of_the_week',
        ),
        migrations.AddField(
            model_name='timeschedule',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeschedule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeschedule',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
