# Generated by Django 2.1.1 on 2019-05-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_auto_20190512_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeschedule',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeschedule',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
